Add script for transferring files to web server

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,19 +1,23 @@
 #!/usr/bin/env bash
-#Transfer a file from client to server
-if [ $# -lt 4 ]; then
-  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-  exit 1
+
+# Check if the number of parameters is less than 4
+if [ "$#" -lt 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
 fi
 
-path_to_file=$1
-ip=$2
-username=$3
-path_to_ssh_key=$4
+# Assign parameters to variables
+FILE_PATH=$1
+SERVER_IP=$2
+USERNAME=$3
+SSH_KEY_PATH=$4
 
-scp -o StrictHostKeyChecking=no -i $path_to_ssh_key $path_to_file $username@$ip:~/
+# Use scp to transfer the file to the user home directory on the server
+scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME@$SERVER_IP":~/
 
-
-
-
-
-
+# Check if scp command was successful
+if [ "$?" -eq 0 ]; then
+    echo "File transfer successful!"
+else
+    echo "File transfer failed."
+fi
